### ISSUE TITLE
Refactor for WSL

### ISSUE THREAD

**Issue by znmeb** [AlgoCompSynth/AlgoCompSynth-One#37]
This was supposed to be in 1.0.0 but the base image has vanished from NGC. So it's getting moved to 1.1.0.

**Comment by mihow** [comment]
I look forward to testing this @znmeb! My main environment is Ubuntu 20.04 on bare metal, but I can boot into Windows and test in my WSL environment as well. I currently have an NVIDIA GTX 1080 and RTX 3060 both installed and the CUDA toolkit working in the environments mentioned above. I am happy to see someone experimenting with algorithmic music and PyTorch!

**Comment by znmeb** [comment]
> I look forward to testing this @znmeb! My main environment is Ubuntu 20.04 on bare metal, but I can boot into Windows and test in my WSL environment as well. I currently have an NVIDIA GTX 1080 and RTX 3060 both installed and the CUDA toolkit working in the environments mentioned above. I am happy to see someone experimenting with algorithmic music and PyTorch!

Thanks! I've been working on another project but I should be able to get back to this next week. I do have a bare metal Ubuntu 20.04 laptop with a 1650 Ti GPU I can test on, although I will probably upgrade to 22.04 because Ubuntu Studio has newer packages.

**Comment by znmeb** [comment]
Done for WSL - no plan at the moment to test on straight Linux install though.
